### ISSUE TITLE
Remove extra Tomcat <host> in Lucee install's server.xml

### ISSUE THREAD

**Issue by bdw429s** [utdream/CFML-Installers#70]
When installing Lucee, Tomcat's server.xml has two `<host>` entries even though there is only one default site.  This was tripping someone up on the CFML Slack team the other day since they changed the doc root of one host but was still hitting the other.

Configure the `defaulthost` in the `<engine>` tag to point to the single-declared host so it can be hit from any hostname and will still work.

**Comment by utdream** [comment]
That extra host is basically a left-over from configuring the default host on Windows machines. However, I removed that in the last build because it was still throwing off some windows users and really, it's not necessary if you're using mod_cfml (which the installer does by default). So, I concur it should just be removed.

Adding this update to Lucee 4.5.1.022 patch level 1.
